# Generated by Django 5.2 on 2026-04-21 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analyse d'écart",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="France", max_length=100)),
            ],
            options={
                "verbose_name": "Établissement",
            },
        ),
        migrations.CreateModel(
            name="OrientationField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("domain", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Filière / Domaine",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("coefficient", models.FloatField(default=1.0)),
            ],
            options={
                "verbose_name": "Matière",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Élève / Étudiant"),
                            ("PARENT", "Parent / Tuteur"),
                            ("MENTOR", "Enseignant / Conseiller"),
                            ("INSTITUTION", "Établissement"),
                            ("ADMIN", "Administrateur"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("BULLETIN", "Bulletin scolaire"),
                            ("DIPLOME", "Diplôme"),
                            ("ATTESTATION", "Attestation"),
                            ("CERTIFICAT", "Certificat"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Déclaré"),
                            ("DOCUMENTED", "Documenté"),
                            ("VERIFIED", "Vérifié"),
                        ],
                        default="DECLARED",
                        max_length=12,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "Haute"),
                            ("MEDIUM", "Moyenne"),
                            ("LOW", "Faible"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("deadline_months", models.PositiveSmallIntegerField(default=3)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "gap_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="scholarpath.gapanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action d'amélioration",
                "ordering": ["priority", "deadline_months"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("ALERT", "Alerte"),
                            ("OPPORTUNITY", "Opportunité"),
                            ("VERIFICATION", "Vérification"),
                            ("INFO", "Information"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="gapanalysis",
            name="orientation_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="scholarpath.orientationfield",
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("6e", "6ème"),
                            ("5e", "5ème"),
                            ("4e", "4ème"),
                            ("3e", "3ème"),
                            ("2nde", "Seconde"),
                            ("1ere", "Première"),
                            ("Term", "Terminale"),
                            ("Bac+1", "Bac+1"),
                            ("Bac+2", "Bac+2"),
                            ("Bac+3", "Bac+3"),
                            ("Bac+4", "Bac+4"),
                            ("Bac+5", "Bac+5"),
                        ],
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("languages", models.CharField(blank=True, max_length=255)),
                ("completion_score", models.FloatField(default=0.0)),
                ("reliability_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scholarpath.institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil élève",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fit_score", models.FloatField()),
                ("justification", models.TextField()),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orientation_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scholarpath.orientationfield",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="scholarpath.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="ProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_score", models.FloatField()),
                ("reliability_score", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="scholarpath.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal de progression",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="scholarpath.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centre d'intérêt",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("target_year", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "orientation_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scholarpath.orientationfield",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="scholarpath.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif",
            },
        ),
        migrations.AddField(
            model_name="gapanalysis",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gap_analyses",
                to="scholarpath.studentprofile",
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ASSOCIATIF", "Associatif"),
                            ("COMPETITION", "Compétition"),
                            ("STAGE", "Stage"),
                            ("PROJET", "Projet personnel"),
                            ("BENEVOLE", "Bénévolat"),
                            ("CERTIFICATION", "Certification"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Déclaré"),
                            ("DOCUMENTED", "Documenté"),
                            ("VERIFIED", "Vérifié"),
                        ],
                        default="DECLARED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="scholarpath.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="orientationfield",
            name="required_subjects",
            field=models.ManyToManyField(blank=True, to="scholarpath.subject"),
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_year", models.CharField(max_length=9)),
                (
                    "trimester",
                    models.CharField(
                        choices=[
                            ("T1", "Trimestre 1"),
                            ("T2", "Trimestre 2"),
                            ("T3", "Trimestre 3"),
                            ("S1", "Semestre 1"),
                            ("S2", "Semestre 2"),
                            ("AN", "Annuel"),
                        ],
                        max_length=3,
                    ),
                ),
                ("grade", models.FloatField()),
                ("max_grade", models.FloatField(default=20.0)),
                ("appreciation", models.TextField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Déclaré"),
                            ("DOCUMENTED", "Documenté"),
                            ("VERIFIED", "Vérifié"),
                        ],
                        default="DECLARED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="scholarpath.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scholarpath.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin / Note",
                "ordering": ["-school_year", "trimester", "subject__name"],
            },
        ),
    ]
